detectors:
  IrresponsibleModule:
    enabled: false

  DuplicateMethodCall:
    enabled: false

  UtilityFunction:
    public_methods_only: true

directories:
  "db/":
    FeatureEnvy: 
      enabled: false
    UncommunicativeVariableName:
      enabled: false
    TooManyStatements:
      enabled: false
