Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 150

Metrics/BlockLength:
  Max: 100
  
AllCops:
  Exclude:
    - 'bin/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'config/**/*'
    - 'spec/**/*'
    - 'lib/tasks/cucumber.rake'
    - 'features/support/env.rb'
