default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  username: <%= ENV.fetch('RAILS_DB_USER', 'rails') %>
  password: <%= ENV.fetch('RAILS_DB_PASSWORD', 'rails') %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: my_kufar_development

test:
  <<: *default
  database: my_kufar_test

production:
  <<: *default
  database: my_kufar_production
